name: Bug Report (中文)
description: 反馈使用中遇到的BUG
title: '[BUG] '
labels: ['bug']
body:
  - type: checkboxes
    id: precheck
    attributes:
      label: '我的问题已经排除以下情况:'
      options:
        - label: 已确认使用的是本插件的最新版本
          required: true
        - label: 已排查过是否由于其他插件冲突引起
          required: true
        - label: 已排查过是否由于权限问题引起(尝试/op假人后仍存在此问题)
          required: true
  - type: input
    id: plugin-version
    attributes:
      label: 插件版本
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: server-core
    attributes:
      label: 服务端核心与版本
      placeholder: Paper 1.21.11
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 描述现象
      placeholder: 请输入问题的简短描述
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 如何复现 [可选]
      description: 如果需要一定的操作步骤才能复现问题，请在此处描述
      placeholder: |-
        1. 
        2. 
        3.
  - type: textarea
    id: other_info
    attributes:
      label: 其他有帮助的信息 [可选]
      description: 提供一些有帮助的信息以协助定位问题，如控制台报错或截图等
      placeholder: |-
        [20:00:00 ERROR]: ...